name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: ci
  PORT: 3000
  SKIP_PREFLIGHT_CHECK: true


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        redis-version: [7]
        mongodb-version: ['6.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - uses: actions/cache@v3
      with:
        path: node_modules/
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-modules-server-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-modules-server-

    - uses: actions/cache@v3
      with:
        path: client/node_modules/
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-modules-client-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-modules-client-


    - name: Install dependencies
      run: |
        npm install --force
        cd client && npm install --force

    - name: Build
      run: npm run build

    - name: Start server
      run: nohup npm run start &

    - name: Wait for server to start
      run: sleep 3

    - name: Test
      run: npm run test
